<a href="https://colab.research.google.com/github/szsctt/learn_torch/blob/main/learn_torch_1_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

##Tensors

From the [Pytorch documentation](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html).

Tensors are like ndarrays in Numpy, but optimized for autodifferentiation and can run on different hardware (e.g. GPUs).

### Initializing a tensor

Tensors can be created from literals: 

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(data)
print(x_data)

[[1, 2], [3, 4]]
tensor([[1, 2],
        [3, 4]])


And also from NumPy arrays

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


And from other tensors.  The properties (shape, data type) of the tensor remain the same unless overridden.

In [4]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4833, 0.8072],
        [0.6255, 0.2796]]) 



### Tensor attributes

The three main attributes of a tensor is its shape, datatype and the device on which it is stored.


In [5]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


`shape` determines the dimensions of the tensor.

In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0769, 0.5253, 0.7031],
        [0.8172, 0.9640, 0.7045]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Operations on Tensors

There are many operations that can be performed on tensors, which are detailed in [the documentation](https://pytorch.org/docs/stable/torch.html).

Operations can be run on a GPU or CPU.  Typically, running on a GPU is faster.

In collab, allocate a GPU by going to Runtime > Change runtime type > GPU.

By default, tensors are created on CPU.  We can move them to a GPU by using the `.to()` method.  Copying large items can be compute- and memory-intensive.



In [7]:
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

Many operations are similar to NumPy, for example indexing and slicing.

In [9]:
tensor = torch.ones(4,4)
print(f"First row {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[..., -1]}")

# re-assign column
tensor[:,1] = 0
print(tensor)

First row tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Use `torch.cat()` to concatenate tensors along a given dimension.

In [11]:
torch.cat((tensor, tensor, tensor), dim=1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

There's also [`torch.stack()`](https://pytorch.org/docs/stable/generated/torch.stack.html), which is subtly different from `torch.cat()`.

Other atrithmetic operations are available

In [13]:
# transposition and matrix multiplication 

y1 = tensor @ tensor.T 
print(y1)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [14]:
tensor.matmul(tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [15]:
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [16]:
# element-wise product
tensor * tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [17]:
tensor.mul(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [18]:
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Single-element tensors (for example, the results of aggregations) can be converted into python values using `item()`

In [21]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


Tensors can be modified in-place, although this is not encouraged becuase it makes differentiation difficult because of a loss of history.

Operations that modify tensors in-place end in `_`, for example `x.copy_()`, `x.t_().`

In [22]:
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


### NumPy and tensors

Tensors and numpy arrays can share the same location in memory, so changing one will change the other.

In [23]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [24]:
# a change in a torch array affects the numpy array
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [25]:
# a change in the numpy array affects the torch array
np.add(1, n, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]
